
  # 邮件设置
  mail:
    host: smtp.qq.com
    username: 504048698
    password: az
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
#收件邮箱
spring.boot.admin.notify.mail.to: 504048698@qq.com
#发件邮箱
spring.boot.admin.notify.mail.from: 504048698@qq.com

myConfig: "成功鸭"

spring:
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #设置采样深度为1
  sleuth:
    sampler:
      rate: 1





